component: express
name: express-avbMgFuNB
org: '1258675334'
app: test
stage: prod
inputs:
  src:
    src: ./
    exclude:
      - .env
      - node_modules/**
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: true
    timeout: 3
    memorySize: 128
  layers:
    - name: '${output:${stage}:${app}:test-layer.name}'
      version: '${output:${stage}:${app}:test-layer.version}'
