version: '3'
services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    # network_mode: 'host'
    ports:
      - '8500:7500'
      - '8000:7000'
      - '10000:9000'
    restart: always
    volumes:
      - './frps.ini:/etc/frp/frps.ini'
